name: Rocket.Unturned

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/Rocket.Unturned.yaml'
      - 'Rocket.Unturned/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/Rocket.Unturned.yaml'
      - 'Rocket.Unturned/**'

jobs:
  build:
    name: "Rocket.Unturned Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      name: Setup .NET
      with:
        dotnet-version: 8.x
        
    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: Rocket.Unturned
        github_token: ${{ secrets.PAT }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true