name: Rocket.API

on:
  create:
    tags:
      - "*"
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/Rocket.API.yaml'
      - 'Rocket/Rocket.API/**'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/Rocket.API.yaml'
      - 'Rocket/Rocket.API/**'

jobs:
  build:
    name: "Rocket.API Build"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - uses: actions/setup-dotnet@v4
      name: Setup .NET
      with:
        dotnet-version: 8.x

    - uses: ./.github/actions/project-build
      id: project-build
      with:
        project_path: Rocket/Rocket.API
        github_token: ${{ secrets.PAT }}
        nuget_key: ${{ secrets.NUGET_DEPLOY_KEY }}
        nuget_push: true